### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by carlosbdw** [rutan/compac-reader#1]
npm i

node-pre-gyp
 ERR! Tried to download(404): https://static.realm.io/node-pre-gyp/realm-v0.15.4-node-v57-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for realm@0.15.4 and node@8.4.0 (node-v57 ABI) (falling back to source compile with node-gyp) 

gradlew assembleRelease

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/xxx/Documents/GitHub/compac-reader/android/app/build.gradle' line: 119

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find property 'TORIPOTA_RELEASE_STORE_FILE' on SigningConfig_Decorated{name=release, storeFile=null, storePassword=null, keyAlias=null, keyPassword=null, storeType=null}.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by rutan** [comment]
Thanks report ! :yum:
I fix this problem in #4 . Please try `npm install` and build.
